server:
  port: 8111

management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  application:
    name: order
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
#        namespace: 7049a3d5-44ac-4dad-9e85-3fdc214fb790
    sentinel:
      transport:
        dashboard: localhost:9999
      filter:
        enabled: true
  main:
    allow-bean-definition-overriding: true
  profiles:
    include: ribbon-sentinel,feign-sentinel