# feign-client-sentinel
feign:
  client:
    config:
      product-center:
        loggerLevel: full
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50
  sentinel:
    enabled: true