server:
  port: 8110

management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  application:
    name: order
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:9999
      filter:
        enabled: true
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: ribbon-sentinel,feign-sentinel