server:
  port: 8210

management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  application:
    name: stock

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:9999
      filter:
        enabled: true